spring.application.name=expensetracker

spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=shahid19

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
